#!/bin/bash
#
# bl-tint2restart to be used by bl-tint2-pipemenu
#   Written by damo <damo@bunsenlabs.org> for BunsenLabs Linux, April 2015
# and johnraff <john@bunsenlabs.org> July 2015

declare -A commands # associative array

while read pid cmd; do
    if [[ ${cmd%% *} = tint2 ]]; then
        kill "$pid"
        commands[$cmd]=1 # duplicate commands will be launched only once
    fi
done <<< "$(pgrep -a tint2)"

sleep 1

# any processes still running will be killed with SIGKILL
while read pid cmd; do
    if [[ ${cmd%% *} = tint2 ]]; then
        kill -KILL "$pid"
        commands[$cmd]=1
    fi
done <<< "$(pgrep -a tint2)"

sleep 1
for i in "${!commands[@]}" # go through the indexes
do
    (setsid $i &)
    sleep 0.1
done

sleep 1
bl-compositor --restart  # restart compositor

exit 0
