#!/bin/bash
# BunsenLabs User Set-up

# USER="$1" USER is exported by lightdm

[ -f "/home/$USER/.config/bunsen/bl-setup" ] && exit

cd /etc/skel
tar cpzf skel.tar.gz .
mv skel.tar.gz /home/$USER/skel.tar.gz
cd /home/$USER
tar --backup -xpsf skel.tar.gz
rm skel.tar.gz

[ -f "/home/$USER/.gtk-bookmarks" ] && {
    rpl -q 'REPLACEME' $USER /home/$USER/.gtk-bookmarks > /dev/null 2>&1
}

ln -s /usr/share/backgrounds /home/$USER/Pictures/wallpapers/shared

mkdir -p /home/$USER/.config/bunsen # this should already exist
touch /home/$USER/.config/bunsen/bl-setup
chown -R $USER:$USER /home/$USER

exit
