#!/bin/bash

HELP="Call notify-send for all current X users.
Passed arguments are sent on as-is.
This script must be run as root."


required_commands=(notify-send) #array

error_exit() {
    echo "$0 error: $1" >&2
    exit 1
}

missing_commands=
for i in "${required_commands[@]}"
do
    hash $i || missing_commands+=" $i"
done
[[ $missing_commands ]] && error_exit "This script requires the following commands: $missing_commands
Please install the packages containing the missing commands
and rerun the script."

case $1 in
--help|-h)
    echo "$HELP"
    exit
    ;;
esac

[[ $( id -u ) -eq 0 ]] || error_exit "This script must be run as root."

declare -A disps usrs
usrs=()
disps=()

for i in $(users);do
    [[ $i = root ]] && continue
    usrs[$i]=1
done # unique names

for u in "${!usrs[@]}"; do
    for i in $(ps e -u "$u" | sed -rn 's/.* DISPLAY=(:[0-9]*).*/\1/p');do
        disps[$i]=$u
    done
done

for d in "${!disps[@]}";do
    sudo -u "${disps[$d]}" DISPLAY="$d" notify-send "$@"
done

exit
